### ISSUE TITLE
Leaderboards.loadLeaderboardScores not working in release mode

### ISSUE THREAD

**Issue by congbap** [Abedalkareem/games_services#104]
Leaderboards.loadLeaderboardScores not works when in release build, but works in debug build.

**Comment by Abedalkareem** [comment]
I think you have an issue with your SHA-1, Can you please check the last section of this tutorial (SHA-1)?

https://akdebuging.com/posts/integrate-gamekit-and-google-play-services/

<img width="742" alt="Screenshot 2023-03-06 at 6 32 53 AM" src="https://user-images.githubusercontent.com/14274852/223006309-b93a110d-0ff1-4ad8-a407-d90e77cc761a.png">

**Comment by congbap** [comment]
SHA-1 is OK. Added according to the guide. In release, showLeaderboards and submitScore are fine.

However, loadLeaderboardScores only works in debug mode and doesn't get values in release.

**Comment by booooohdan** [comment]
The same issue for Android and iOS. iOS doesn't use SHA keys, but the behavior literally the same: "Endless loading of result"

**Comment by nicop496** [comment]
I had the same issue. After many hours, I found that the **LeaderboardScoreData model is wrong**, because the JSON that is receiving is something like this:
`
{
  "a": 1,
  "b": 53,
  "c": 53,
  "d": 11245510,
  "e": NicoElGrillo,
  "f": <lots of random letters I don't remember>
}
`
where `"a"` is the rank, `"b"` is the display score, `"c"` is the raw score, "`d`" is the timestamp in milliseconds, `"e"` is the username and I guess that `"f"` is the user profile photo.

So **to fix the error you have to go the file and modify `LeaderboardScoreData.fromJson` factory method**.

I hope this helps, and have a nice day.

**Comment by booooohdan** [comment]
@Abedalkareem can you check nicop496's comment please, and make changes if this guy is correct?

**Comment by Abedalkareem** [comment]
Thanks guys,

I'll check that and do it maybe tomorrow.

**Comment by Abedalkareem** [comment]
Hi, 
After debugging this issue I discovered it's because of ProGuard, for now, can you try to add your models to ProGuard rules as below:

-keep class your.data.object.modals.package.** { <fields>; }

**Comment by congbap** [comment]
> Hi, After debugging this issue I discovered it's because of ProGuard, for now, can you try to add your models to ProGuard rules as below:
> 
> -keep class your.data.object.modals.package.** { ; }

I don't use the model. I just use this package. The model belongs to this.

**Comment by congbap** [comment]
> Hi, After debugging this issue I discovered it's because of ProGuard, for now, can you try to add your models to ProGuard rules as below:
> 
> -keep class your.data.object.modals.package.** { ; }

take a look at this comment
https://github.com/Abedalkareem/games_services/issues/90#issuecomment-1292593192
