### ISSUE TITLE
Can't able to Sign in Play Game Services (Andriod)

### ISSUE THREAD

**Issue by utkarsh-karnik** [Abedalkareem/games_services#63]
This Package is working fine for Game Center Sign In iOS Devices, But On Android, It's not working in android...I've set up Everything completely fine (Google Play Console, Google Cloud O Auth ID, ) as per the official written documentation for this package 

![image](https://user-images.githubusercontent.com/99238514/171428114-ee1667b8-9c0b-49d3-84c6-b5fc1be68f7b.png)

**I've searched on the Internet and found some solutions...but none of the solutions didn't work ...I've added the SHA-1 in Firebase Console, Created the O Auth Token, and Published the Consent Screen for the same SHA-1 But it still gives me the same exception.**

**Comment by jonafeucht** [comment]
How are you calling the app id? Like this: ```<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="your_app_id" />```?

**Comment by jonafeucht** [comment]
The proper way to do it is either put a \u003 before your app id, like this: 
`<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\u003your_app_id" />`

or the better way, where you don't have to change anything since it's fetching the app id for you:
`<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="@string/app_id" />`

**Comment by Abedalkareem** [comment]
Hi,
Can you please try this?
https://stackoverflow.com/questions/47437678/why-do-i-get-com-google-android-gms-common-api-apiexception-10

**Comment by utkarsh-karnik** [comment]
Thanks @jonafeucht It worked...I had not set the app-id in a proper way ...Your answer really helped me!
