### ISSUE TITLE
Achievements.loadAchievements weird

### ISSUE THREAD

**Issue by cenyG** [Abedalkareem/games_services#90]
`Achievements.loadAchievements()` not works when in `release` build, but works in `debug` build.

Other methods `GamesServices.signIn()`, `GamesServices.getPlayerName()`, `GamesServices.getPlayerScore(...)` work for both.
So no idea what's going on.

I think it's for any Android, but I tested on Android 12, flutter:3.3.3

**Comment by cenyG** [comment]
log for info
`I/flutter (13329): type 'Null' is not a subtype of type 'String'
I/flutter (13329): #0      new AchievementItemData.fromJson (package:games_services/src/models/achievement_item_data.dart:38)
I/flutter (13329): #1      Achievements.loadAchievements.<anonymous closure> (package:games_services/src/achievements.dart:20)
I/flutter (13329): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
I/flutter (13329): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342)
I/flutter (13329): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
I/flutter (13329): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
I/flutter (13329): #6      new List.of (dart:core-patch/array_patch.dart:51)
I/flutter (13329): #7      Iterable.toList (dart:core/iterable.dart:470)
I/flutter (13329): #8      Achievements.loadAchievements (package:games_services/src/achievements.dart:20)
I/flutter (13329): <asynchronous suspension>
I/flutter (13329): #9      UserInfoProvider.init (package:coutries_quiz/providers/user_info_provider.dart:31)`

**Comment by theLee3** [comment]
This is due to code obfuscation in the release build. This can be confirmed/remedied by disabling obfuscation. Update the release build to not obfuscate with the following steps.

1. Add the file `android/app/proguard-rules.pro` to your project with the following line:
```
-dontobfuscate
```
2. Update the release build in `android/app/build.grade`.
```
buildTypes {
    release {
        ...
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

This is a temporary solution, and we should find which specific classes we are using need to be excluded from obfuscation.
Places of interests:
1. Gson (as noted [here](https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg))
2. Kotlin coroutines?
3. Our model classes that are serialized ?

**Comment by booooohdan** [comment]
@Abedalkareem make a new package release, please. You made a lot of useful changes in develop branch

**Comment by Abedalkareem** [comment]
@booooohdan 

A new version released.

3.0.1
