### ISSUE TITLE
submitScore value only allows for integers

### ISSUE THREAD

**Issue by davidferraro** [Abedalkareem/games_services#95]
The submitScore function only allows for integers for the value parameter, but the leaderboards for both Play Games Services and Game Center allow for decimal values, duration (which you could workaround by sending number of seconds and doing a custom leadboard view), and currency values. Would it be possible to override the submitScore to allow for different value types?

Also, currently I am able to sign in for both android and iOS and I believe pull the leaderboard data (empty lists because there are no scores) but the result of the submitScore promise returns null and no scores are getting to the leaderboard. The Apple Game Center leaderboards in the Game Center say "Not Live" and the configuraton in the Google Play Games Services has this step still unresolved "Add the Play Games Services SDK to your production APK to use the APIs". Seems for both I need to just push a release including games_services to production before really testing score submission? Does that jive with other people's experiences setting this up or am I missing something? Thanks!

**Comment by theLee3** [comment]
Both platforms actually only accept integers for scores. They are displayed in the selected format by the platform. If using a custom UI, you would have to convert the integer values yourself. You can learn how to submit your score according to format for Play Games Services [here](https://developers.google.com/games/services/common/concepts/leaderboards#score_formatting). Information for Game Center can be found [here](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/GameKit_Guide/Achievements/Achievements.html), specifically, in the section titled "Leaderboards Require a Scoring Mechanism".

You should be able to push to a test track on the Play Store and TestFlight on the App Store in order to test uploading to leaderboards, as well as testing Achievements.
